// Datos mock realistas para AGRO CAMPO

export const predios = [
  {
    id: '1',
    nombre: 'Puerto Arturo',
    ubicacion: 'Vereda El Silencio, Palmira',
    hectareas: 250,
    lotes: 12,
  },
  {
    id: '2',
    nombre: 'La Vega',
    ubicacion: 'Corregimiento La María, Buga',
    hectareas: 180,
    lotes: 8,
  },
  {
    id: '3',
    nombre: 'El Paraíso',
    ubicacion: 'Vereda La Iberia, Tuluá',
    hectareas: 320,
    lotes: 15,
  },
  {
    id: '4',
    nombre: 'San Rafael',
    ubicacion: 'Corregimiento Rozo, Palmira',
    hectareas: 145,
    lotes: 6,
  },
  {
    id: '5',
    nombre: 'Villa Nueva',
    ubicacion: 'Vereda El Carmen, Ginebra',
    hectareas: 210,
    lotes: 10,
  },
];

export const lotes = [
  {
    id: 'l1',
    nombre: 'Lote 1 – Norte',
    predioId: '1',
    predio: 'Puerto Arturo',
    fechaSiembra: '2018-03-15',
    anoSiembra: 2018,
    variedad: 'Elaeis Guineensis',
    semillas: ['Elaeis Guineensis', 'Híbrido OxG'],
    hectareas: 45,
    totalPalmas: 850,
    sublotes: 5,
  },
  {
    id: 'l2',
    nombre: 'Lote 2 – Sur',
    predioId: '1',
    predio: 'Puerto Arturo',
    fechaSiembra: '2019-06-22',
    anoSiembra: 2019,
    variedad: 'Híbrido OxG',
    semillas: ['Híbrido OxG'],
    hectareas: 38,
    totalPalmas: 720,
    sublotes: 4,
  },
  {
    id: 'l3',
    nombre: 'Lote 3 – Este',
    predioId: '2',
    predio: 'La Vega',
    fechaSiembra: '2020-01-10',
    anoSiembra: 2020,
    variedad: 'Elaeis Guineensis',
    semillas: ['Elaeis Guineensis'],
    hectareas: 52,
    totalPalmas: 980,
    sublotes: 6,
  },
  {
    id: 'l4',
    nombre: 'Lote A – Central',
    predioId: '3',
    predio: 'El Paraíso',
    fechaSiembra: '2017-09-05',
    anoSiembra: 2017,
    variedad: 'Compacta E3',
    semillas: ['Compacta E3'],
    hectareas: 62,
    totalPalmas: 1240,
    sublotes: 8,
  },
  {
    id: 'l5',
    nombre: 'Lote B – Occidental',
    predioId: '3',
    predio: 'El Paraíso',
    fechaSiembra: '2021-02-18',
    anoSiembra: 2021,
    variedad: 'Híbrido OxG',
    semillas: ['Híbrido OxG', 'Elaeis Guineensis'],
    hectareas: 55,
    totalPalmas: 1045,
    sublotes: 7,
  },
  {
    id: 'l6',
    nombre: 'Lote 1 – Principal',
    predioId: '4',
    predio: 'San Rafael',
    fechaSiembra: '2019-11-12',
    anoSiembra: 2019,
    variedad: 'Elaeis Guineensis',
    semillas: ['Elaeis Guineensis'],
    hectareas: 48,
    totalPalmas: 912,
    sublotes: 6,
  },
  {
    id: 'l7',
    nombre: 'Lote Alpha',
    predioId: '5',
    predio: 'Villa Nueva',
    fechaSiembra: '2020-07-25',
    anoSiembra: 2020,
    variedad: 'Híbrido OxG',
    semillas: ['Híbrido OxG'],
    hectareas: 70,
    totalPalmas: 1330,
    sublotes: 9,
  },
];

// Sublotes por lote
export const sublotes = [
  // Lote 1 - Norte (l1) - 5 sublotes
  { id: 'sl1-1', nombre: 'Sublote A', loteId: 'l1', estado: 'Activo' as const },
  { id: 'sl1-2', nombre: 'Sublote B', loteId: 'l1', estado: 'Activo' as const },
  { id: 'sl1-3', nombre: 'Sublote C', loteId: 'l1', estado: 'Activo' as const },
  { id: 'sl1-4', nombre: 'Sublote D', loteId: 'l1', estado: 'Activo' as const },
  { id: 'sl1-5', nombre: 'Sublote E', loteId: 'l1', estado: 'Activo' as const },
  
  // Lote 2 - Sur (l2) - 4 sublotes
  { id: 'sl2-1', nombre: 'Sublote A', loteId: 'l2', estado: 'Activo' as const },
  { id: 'sl2-2', nombre: 'Sublote B', loteId: 'l2', estado: 'Activo' as const },
  { id: 'sl2-3', nombre: 'Sublote C', loteId: 'l2', estado: 'Activo' as const },
  { id: 'sl2-4', nombre: 'Sublote D', loteId: 'l2', estado: 'Activo' as const },
  
  // Lote 3 - Este (l3) - 6 sublotes
  { id: 'sl3-1', nombre: 'Sublote A', loteId: 'l3', estado: 'Activo' as const },
  { id: 'sl3-2', nombre: 'Sublote B', loteId: 'l3', estado: 'Activo' as const },
  { id: 'sl3-3', nombre: 'Sublote C', loteId: 'l3', estado: 'Activo' as const },
  { id: 'sl3-4', nombre: 'Sublote D', loteId: 'l3', estado: 'Activo' as const },
  { id: 'sl3-5', nombre: 'Sublote E', loteId: 'l3', estado: 'Activo' as const },
  { id: 'sl3-6', nombre: 'Sublote F', loteId: 'l3', estado: 'Activo' as const },
  
  // Lote A - Central (l4) - 8 sublotes
  { id: 'sl4-1', nombre: 'Sublote A', loteId: 'l4', estado: 'Activo' as const },
  { id: 'sl4-2', nombre: 'Sublote B', loteId: 'l4', estado: 'Activo' as const },
  { id: 'sl4-3', nombre: 'Sublote C', loteId: 'l4', estado: 'Activo' as const },
  { id: 'sl4-4', nombre: 'Sublote D', loteId: 'l4', estado: 'Activo' as const },
  { id: 'sl4-5', nombre: 'Sublote E', loteId: 'l4', estado: 'Activo' as const },
  { id: 'sl4-6', nombre: 'Sublote F', loteId: 'l4', estado: 'Activo' as const },
  { id: 'sl4-7', nombre: 'Sublote G', loteId: 'l4', estado: 'Activo' as const },
  { id: 'sl4-8', nombre: 'Sublote H', loteId: 'l4', estado: 'Activo' as const },
  
  // Lote B - Occidental (l5) - 7 sublotes
  { id: 'sl5-1', nombre: 'Sublote A', loteId: 'l5', estado: 'Activo' as const },
  { id: 'sl5-2', nombre: 'Sublote B', loteId: 'l5', estado: 'Activo' as const },
  { id: 'sl5-3', nombre: 'Sublote C', loteId: 'l5', estado: 'Activo' as const },
  { id: 'sl5-4', nombre: 'Sublote D', loteId: 'l5', estado: 'Activo' as const },
  { id: 'sl5-5', nombre: 'Sublote E', loteId: 'l5', estado: 'Activo' as const },
  { id: 'sl5-6', nombre: 'Sublote F', loteId: 'l5', estado: 'Activo' as const },
  { id: 'sl5-7', nombre: 'Sublote G', loteId: 'l5', estado: 'Activo' as const },
  
  // Lote 1 - Principal (l6) - 6 sublotes
  { id: 'sl6-1', nombre: 'Sublote A', loteId: 'l6', estado: 'Activo' as const },
  { id: 'sl6-2', nombre: 'Sublote B', loteId: 'l6', estado: 'Activo' as const },
  { id: 'sl6-3', nombre: 'Sublote C', loteId: 'l6', estado: 'Activo' as const },
  { id: 'sl6-4', nombre: 'Sublote D', loteId: 'l6', estado: 'Activo' as const },
  { id: 'sl6-5', nombre: 'Sublote E', loteId: 'l6', estado: 'Activo' as const },
  { id: 'sl6-6', nombre: 'Sublote F', loteId: 'l6', estado: 'Activo' as const },
  
  // Lote Alpha (l7) - 9 sublotes
  { id: 'sl7-1', nombre: 'Sublote A', loteId: 'l7', estado: 'Activo' as const },
  { id: 'sl7-2', nombre: 'Sublote B', loteId: 'l7', estado: 'Activo' as const },
  { id: 'sl7-3', nombre: 'Sublote C', loteId: 'l7', estado: 'Activo' as const },
  { id: 'sl7-4', nombre: 'Sublote D', loteId: 'l7', estado: 'Activo' as const },
  { id: 'sl7-5', nombre: 'Sublote E', loteId: 'l7', estado: 'Activo' as const },
  { id: 'sl7-6', nombre: 'Sublote F', loteId: 'l7', estado: 'Activo' as const },
  { id: 'sl7-7', nombre: 'Sublote G', loteId: 'l7', estado: 'Activo' as const },
  { id: 'sl7-8', nombre: 'Sublote H', loteId: 'l7', estado: 'Activo' as const },
  { id: 'sl7-9', nombre: 'Sublote I', loteId: 'l7', estado: 'Activo' as const },
];

// Palmas por sublote (generando palmas para cada sublote)
// Función helper para generar palmas
const generarPalmas = (subloteId: string, cantidad: number) => {
  const palmas = [];
  for (let i = 1; i <= cantidad; i++) {
    palmas.push({
      id: `${subloteId}-p${i}`,
      codigo: `P-${subloteId.toUpperCase()}-${i.toString().padStart(3, '0')}`,
      subloteId: subloteId,
      variedad: 'Elaeis Guineensis',
      estado: 'Activo' as const,
    });
  }
  return palmas;
};

export const palmas = [
  // Lote 1 - Norte (850 palmas / 5 sublotes = ~170 por sublote)
  ...generarPalmas('sl1-1', 170),
  ...generarPalmas('sl1-2', 170),
  ...generarPalmas('sl1-3', 170),
  ...generarPalmas('sl1-4', 170),
  ...generarPalmas('sl1-5', 170),
  
  // Lote 2 - Sur (720 palmas / 4 sublotes = 180 por sublote)
  ...generarPalmas('sl2-1', 180),
  ...generarPalmas('sl2-2', 180),
  ...generarPalmas('sl2-3', 180),
  ...generarPalmas('sl2-4', 180),
  
  // Lote 3 - Este (980 palmas / 6 sublotes = ~163 por sublote)
  ...generarPalmas('sl3-1', 164),
  ...generarPalmas('sl3-2', 164),
  ...generarPalmas('sl3-3', 163),
  ...generarPalmas('sl3-4', 163),
  ...generarPalmas('sl3-5', 163),
  ...generarPalmas('sl3-6', 163),
  
  // Lote A - Central (1240 palmas / 8 sublotes = 155 por sublote)
  ...generarPalmas('sl4-1', 155),
  ...generarPalmas('sl4-2', 155),
  ...generarPalmas('sl4-3', 155),
  ...generarPalmas('sl4-4', 155),
  ...generarPalmas('sl4-5', 155),
  ...generarPalmas('sl4-6', 155),
  ...generarPalmas('sl4-7', 155),
  ...generarPalmas('sl4-8', 155),
  
  // Lote B - Occidental (1045 palmas / 7 sublotes = ~149 por sublote)
  ...generarPalmas('sl5-1', 149),
  ...generarPalmas('sl5-2', 149),
  ...generarPalmas('sl5-3', 149),
  ...generarPalmas('sl5-4', 150),
  ...generarPalmas('sl5-5', 149),
  ...generarPalmas('sl5-6', 150),
  ...generarPalmas('sl5-7', 149),
  
  // Lote 1 - Principal (912 palmas / 6 sublotes = 152 por sublote)
  ...generarPalmas('sl6-1', 152),
  ...generarPalmas('sl6-2', 152),
  ...generarPalmas('sl6-3', 152),
  ...generarPalmas('sl6-4', 152),
  ...generarPalmas('sl6-5', 152),
  ...generarPalmas('sl6-6', 152),
  
  // Lote Alpha (1330 palmas / 9 sublotes = ~148 por sublote)
  ...generarPalmas('sl7-1', 148),
  ...generarPalmas('sl7-2', 148),
  ...generarPalmas('sl7-3', 148),
  ...generarPalmas('sl7-4', 148),
  ...generarPalmas('sl7-5', 147),
  ...generarPalmas('sl7-6', 148),
  ...generarPalmas('sl7-7', 148),
  ...generarPalmas('sl7-8', 147),
  ...generarPalmas('sl7-9', 148),
];

export const colaboradores = [
  {
    id: 'c1',
    nombres: 'Carlos',
    apellidos: 'Rodríguez García',
    tipoDocumento: 'CC',
    cedula: '1.234.567.890',
    fechaNacimiento: '1990-05-15',
    cargo: 'Operario de Campo',
    modalidadPago: 'Producción',
    salarioBase: 1300000,
    estado: 'Activo',
    eps: 'Sanitas',
    arl: 'Sura',
    fondoPension: 'Porvenir',
    tallaCamisa: 'M',
    tallaPantalon: '32',
    tallaCalzado: '42',
    banco: 'Bancolombia',
    tipoCuenta: 'Ahorros',
    numeroCuenta: '123-456-789',
    fechaIngreso: '2020-03-15',
    telefono: '3201234567',
    email: 'carlos.rodriguez@agrocampo.com',
    direccion: 'Calle 45 #23-67, Palmira',
    estadoCivil: 'Casado',
    contactoEmergencia: 'Laura Rodríguez - 3109876543',
    loteAsignado: 'Lote 1 – Norte',
  },
  {
    id: 'c2',
    nombres: 'María',
    apellidos: 'González López',
    tipoDocumento: 'CC',
    cedula: '2.345.678.901',
    fechaNacimiento: '1988-11-22',
    cargo: 'Operaria de Campo',
    modalidadPago: 'Fijo',
    salarioBase: 1500000,
    estado: 'Activo',
    eps: 'Compensar',
    arl: 'Positiva',
    fondoPension: 'Protección',
    tallaCamisa: 'S',
    tallaPantalon: '28',
    tallaCalzado: '37',
    banco: 'Davivienda',
    tipoCuenta: 'Ahorros',
    numeroCuenta: '987-654-321',
    fechaIngreso: '2019-08-22',
    telefono: '3112345678',
    email: 'maria.gonzalez@agrocampo.com',
    direccion: 'Carrera 12 #8-45, Buga',
    estadoCivil: 'Soltera',
    contactoEmergencia: 'Roberto González - 3156789012',
    loteAsignado: 'Lote 2 – Sur',
  },
  {
    id: 'c3',
    nombres: 'Luis',
    apellidos: 'Martínez Pérez',
    tipoDocumento: 'CC',
    cedula: '3.456.789.012',
    fechaNacimiento: '1985-03-10',
    cargo: 'Supervisor',
    modalidadPago: 'Fijo',
    salarioBase: 2000000,
    estado: 'Activo',
    eps: 'Sura',
    arl: 'Sura',
    fondoPension: 'Colfondos',
    tallaCamisa: 'L',
    tallaPantalon: '34',
    tallaCalzado: '43',
    banco: 'Banco de Bogotá',
    tipoCuenta: 'Corriente',
    numeroCuenta: '456-789-123',
    fechaIngreso: '2018-01-10',
    telefono: '3187654321',
    email: 'luis.martinez@agrocampo.com',
    direccion: 'Avenida 5N #34-12, Tuluá',
    estadoCivil: 'Casado',
    contactoEmergencia: 'Patricia Martínez - 3145678901',
    loteAsignado: 'Lote A – Central',
  },
  {
    id: 'c4',
    nombres: 'Ana',
    apellidos: 'Ramírez Torres',
    tipoDocumento: 'CC',
    cedula: '4.567.890.123',
    fechaNacimiento: '1995-07-28',
    cargo: 'Operaria de Campo',
    modalidadPago: 'Producción',
    salarioBase: 1300000,
    estado: 'Activo',
    eps: 'Nueva EPS',
    arl: 'Equidad',
    fondoPension: 'Skandia',
    tallaCamisa: 'S',
    tallaPantalon: '28',
    tallaCalzado: '38',
    banco: 'Bancolombia',
    tipoCuenta: 'Ahorros',
    numeroCuenta: '789-123-456',
    fechaIngreso: '2021-05-18',
    telefono: '3123456789',
    email: 'ana.ramirez@agrocampo.com',
    direccion: 'Calle 18 #14-56, Palmira',
    estadoCivil: 'Unión Libre',
    contactoEmergencia: 'Miguel Torres - 3167890123',
    loteAsignado: 'Lote 3 – Este',
  },
  {
    id: 'c5',
    nombres: 'Pedro',
    apellidos: 'Sánchez Ruiz',
    tipoDocumento: 'CC',
    cedula: '5.678.901.234',
    fechaNacimiento: '1992-09-14',
    cargo: 'Operario de Campo',
    modalidadPago: 'Fijo',
    salarioBase: 1400000,
    estado: 'Inactivo',
    eps: 'Salud Total',
    arl: 'Sura',
    fondoPension: 'Porvenir',
    tallaCamisa: 'M',
    tallaPantalon: '32',
    tallaCalzado: '41',
    banco: 'BBVA',
    tipoCuenta: 'Ahorros',
    numeroCuenta: '321-654-987',
    fechaIngreso: '2019-02-10',
    fechaEgreso: '2025-12-31',
    telefono: '3198765432',
    email: 'pedro.sanchez@agrocampo.com',
    direccion: 'Carrera 8 #22-34, Ginebra',
    estadoCivil: 'Casado',
    contactoEmergencia: 'Carmen Ruiz - 3134567890',
    loteAsignado: 'Lote B – Occidental',
  },
  {
    id: 'c6',
    nombres: 'Juliana',
    apellidos: 'Herrera Castillo',
    tipoDocumento: 'CC',
    cedula: '6.789.012.345',
    fechaNacimiento: '1993-04-17',
    cargo: 'Operaria de Campo',
    modalidadPago: 'Producción',
    salarioBase: 1350000,
    estado: 'Activo',
    eps: 'Sanitas',
    arl: 'Positiva',
    fondoPension: 'Porvenir',
    tallaCamisa: 'M',
    tallaPantalon: '30',
    tallaCalzado: '39',
    banco: 'Davivienda',
    tipoCuenta: 'Ahorros',
    numeroCuenta: '654-321-987',
    fechaIngreso: '2022-09-05',
    telefono: '3176543210',
    email: 'juliana.herrera@agrocampo.com',
    direccion: 'Calle 32 #19-45, Buga',
    estadoCivil: 'Soltera',
    contactoEmergencia: 'Rosa Castillo - 3145679012',
    loteAsignado: 'Lote 1 – Principal',
  },
  {
    id: 'c7',
    nombres: 'Roberto',
    apellidos: 'Vargas Mendoza',
    tipoDocumento: 'CC',
    cedula: '7.890.123.456',
    fechaNacimiento: '1987-12-03',
    cargo: 'Jefe de Campo',
    modalidadPago: 'Fijo',
    salarioBase: 3500000,
    estado: 'Activo',
    eps: 'Sura',
    arl: 'Sura',
    fondoPension: 'Colfondos',
    tallaCamisa: 'XL',
    tallaPantalon: '36',
    tallaCalzado: '44',
    banco: 'Bancolombia',
    tipoCuenta: 'Corriente',
    numeroCuenta: '147-258-369',
    fechaIngreso: '2017-04-20',
    telefono: '3209876543',
    email: 'roberto.vargas@agrocampo.com',
    direccion: 'Avenida 6 #28-90, Palmira',
    estadoCivil: 'Casado',
    contactoEmergencia: 'Sandra Mendoza - 3182345678',
    loteAsignado: 'Lote Alpha',
  },
];

export const cuadrillas = [
  {
    id: 'cu1',
    nombre: 'Cuadrilla 1 - Cosecha',
    integrantes: ['c1', 'c2', 'c4'],
  },
  {
    id: 'cu2',
    nombre: 'Cuadrilla 2 - Mantenimiento',
    integrantes: ['c3'],
  },
];

export const nominaPeriodos = [
  {
    id: 'n1',
    periodo: 'Enero 2026 – Primera quincena',
    mes: 1,
    ano: 2026,
    quincena: 1,
    estado: 'CERRADA',
    devengadoTotal: 18500000,
    deduccionesTotal: 2200000,
    netoTotal: 16300000,
  },
  {
    id: 'n2',
    periodo: 'Enero 2026 – Segunda quincena',
    mes: 1,
    ano: 2026,
    quincena: 2,
    estado: 'CERRADA',
    devengadoTotal: 19200000,
    deduccionesTotal: 2350000,
    netoTotal: 16850000,
  },
  {
    id: 'n3',
    periodo: 'Febrero 2026 – Primera quincena',
    mes: 2,
    ano: 2026,
    quincena: 1,
    estado: 'BORRADOR',
    devengadoTotal: 17800000,
    deduccionesTotal: 2100000,
    netoTotal: 15700000,
  },
];

export const viajes = [
  {
    id: 'r1',
    fecha: '2026-03-01',
    placa: 'ABC-123',
    conductor: 'Pedro Gómez',
    lotes: ['Lote 1 – Norte', 'Lote 2 – Sur'],
    gajosEstimados: 12500,
    peso: 18750,
    estado: 'FINALIZADO',
  },
  {
    id: 'r2',
    fecha: '2026-03-02',
    placa: 'DEF-456',
    conductor: 'Juan Ramírez',
    lotes: ['Lote 3 – Este'],
    gajosEstimados: 8200,
    peso: 12300,
    estado: 'EN_PLANTA',
  },
  {
    id: 'r3',
    fecha: '2026-03-03',
    placa: 'GHI-789',
    conductor: 'Carlos Méndez',
    lotes: ['Lote 1 – Norte'],
    gajosEstimados: 9500,
    peso: 14250,
    estado: 'BORRADOR',
  },
];

export const semillas = [
  { id: 's1', tipo: 'Africana', nombre: 'Elaeis Guineensis' },
  { id: 's2', tipo: 'Híbrido', nombre: 'Híbrido OxG' },
  { id: 's3', tipo: 'Compacta', nombre: 'Compacta E3' },
];

export const insumos = [
  { id: 'i1', nombre: 'Fertilizante NPK', unidad: 'KILOGRAMO' },
  { id: 'i2', nombre: 'Herbicida Glifosato', unidad: 'LITRO' },
  { id: 'i3', nombre: 'Insecticida Malathion', unidad: 'GALON' },
  { id: 'i4', nombre: 'Abono orgánico', unidad: 'KILOGRAMO' },
];

export const cargos = [
  { id: 'cg1', nombre: 'Operario de Campo', tipoSalario: 'VARIABLE', salarioBase: 1300000 },
  { id: 'cg2', nombre: 'Operaria de Campo', tipoSalario: 'VARIABLE', salarioBase: 1300000 },
  { id: 'cg3', nombre: 'Supervisor', tipoSalario: 'FIJO', salarioBase: 2000000 },
  { id: 'cg4', nombre: 'Jefe de Campo', tipoSalario: 'FIJO', salarioBase: 3500000 },
  { id: 'cg5', nombre: 'Conductor', tipoSalario: 'FIJO', salarioBase: 1800000 },
];

export const contratos = [
  {
    id: 'con1',
    colaboradorId: 'c1',
    colaboradorNombre: 'Carlos Rodríguez García',
    documento: '1.234.567.890',
    fechaInicio: '2020-03-15',
    fechaTerminacion: null,
    modalidad: 'Indefinido',
    estado: 'Vigente',
    documentoPDF: null,
  },
  {
    id: 'con2',
    colaboradorId: 'c2',
    colaboradorNombre: 'María González López',
    documento: '2.345.678.901',
    fechaInicio: '2019-08-22',
    fechaTerminacion: null,
    modalidad: 'Indefinido',
    estado: 'Vigente',
    documentoPDF: null,
  },
  {
    id: 'con3',
    colaboradorId: 'c3',
    colaboradorNombre: 'Luis Martínez Pérez',
    documento: '3.456.789.012',
    fechaInicio: '2018-01-10',
    fechaTerminacion: null,
    modalidad: 'Indefinido',
    estado: 'Vigente',
    documentoPDF: null,
  },
  {
    id: 'con4',
    colaboradorId: 'c4',
    colaboradorNombre: 'Ana Ramírez Torres',
    documento: '4.567.890.123',
    fechaInicio: '2021-05-18',
    fechaTerminacion: '2026-05-17',
    modalidad: 'Fijo a 5 años',
    estado: 'Vigente',
    documentoPDF: null,
  },
  {
    id: 'con5',
    colaboradorId: 'c5',
    colaboradorNombre: 'Pedro Sánchez Ruiz',
    documento: '5.678.901.234',
    fechaInicio: '2019-02-10',
    fechaTerminacion: '2025-12-31',
    modalidad: 'Fijo',
    estado: 'Terminado',
    documentoPDF: null,
  },
];

export const labores = [
  { id: 'la1', nombre: 'Plateo', tipoPago: 'JORNAL_FIJO', valorBase: 55000, unidad: 'JORNAL' },
  { id: 'la2', nombre: 'Poda', tipoPago: 'POR_PALMA', valorBase: 1200, unidad: 'PALMAS' },
  { id: 'la3', nombre: 'Fertilización', tipoPago: 'JORNAL_FIJO', valorBase: 60000, unidad: 'JORNAL' },
  { id: 'la4', nombre: 'Cosecha', tipoPago: 'POR_PALMA', valorBase: 950, unidad: 'PALMAS' },
];

export const productividadColaboradores = [
  {
    id: 'pc1',
    colaborador: 'Carlos Rodríguez García',
    gajos: 3250,
    kg: 4875,
    jornales: 22,
    rendimiento: 147.5,
    tendencia: 'up',
  },
  {
    id: 'pc2',
    colaborador: 'María González López',
    gajos: 2980,
    kg: 4470,
    jornales: 24,
    rendimiento: 124.2,
    tendencia: 'up',
  },
  {
    id: 'pc3',
    colaborador: 'Luis Martínez Pérez',
    gajos: 1850,
    kg: 2775,
    jornales: 26,
    rendimiento: 71.2,
    tendencia: 'down',
  },
  {
    id: 'pc4',
    colaborador: 'Ana Ramírez Torres',
    gajos: 2650,
    kg: 3975,
    jornales: 20,
    rendimiento: 132.5,
    tendencia: 'stable',
  },
];

export const preciosCosecha = [
  {
    id: 'pr1',
    lote: 'Lote 1 – Norte',
    precioKg: 850,
    produccion: 45000,
    totalEstimado: 38250000,
  },
  {
    id: 'pr2',
    lote: 'Lote 2 – Sur',
    precioKg: 850,
    produccion: 38000,
    totalEstimado: 32300000,
  },
  {
    id: 'pr3',
    lote: 'Lote 3 – Este',
    precioKg: 820,
    produccion: 52000,
    totalEstimado: 42640000,
  },
];

export const kpisDashboard = {
  produccionTotal: 135000,
  kgTotal: 202500,
  gajosTotal: 145800,
  promedioKgGajo: 1.39,
  productividadPromedio: 118.6,
  lluviaAcumulada: 125,
};